acrn-hypervisor: fix build error on python3.9
backport patch to fix build error on python 3.9 due to deprecated
getchildren().

Error log:
| File "acrn-workspace/poky/build-gatesgarth/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/2.3-r0/git/misc/acrn-config/scenario_config/../acpi_gen/asl_gen.py", line 426, in main
| for mmio_dev_node in mmio_dev_nodes.getchildren():
| AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'
| make: *** No rule to make target 'update_config', needed by 'acrn-workspace/poky/build-gatesgarth/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/2.3-r0/build/hypervisor/.config'. Stop.
| make: Leaving directory 'acrn-workspace/poky/build-gatesgarth/master-acrn-sos/work/x86_64-linux/acrn-hypervisor-native/2.3-r0/git/hypervisor'
| WARNING: exit code 1 from a shell command.

Signed-off-by: Lee Chee Yang <chee.yang.lee@intel.com>