acrn-tools: fix build error due to gcc10
Fix build error due to gcc10 default to -fno-common
https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=780d38ee5ecae2d7fbc44a88bc12250e45f2c79c

This is to fix the build error for now. A long term fix needs
to apply to acrn-hypervisor allowing CFLAGS from env to take
place in all Makefile.

Error:
| /yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/recipe-sysroot-native/usr/bin/x86_64-oe-linux/../../libexec/x86_64-oe-linux/gcc/x86_64-oe-linux/10.2.0/ld: /yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/build/misc/tools/acrn-crashlog/acrnprobe/obj/android_events.o:/yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/git/misc/tools/acrn-crashlog/acrnprobe/include/load_conf.h:155: multiple definition of `conf'; /yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/build/misc/tools/acrn-crashlog/acrnprobe/obj/main.o:/yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/git/misc/tools/acrn-crashlog/acrnprobe/include/load_conf.h:155: first defined here
| collect2: error: ld returned 1 exit status
| Makefile:42: recipe for target '/yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/build/misc/tools/acrn-crashlog/acrnprobe/bin/acrnprobe' failed
| make[3]: *** '[/yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/build/misc/tools/acrn-crashlog/acrnprobe/bin/acrnprobe] Error 1
| make[3]: Leaving directory '/yocto/poky-master/build-acrn/master-acrn-sos/work/corei7-64-oe-linux/acrn-tools/2.1-r0/git/misc/tools/acrn-crashlog/acrnprobe'

Signed-off-by: Lee Chee Yang <chee.yang.lee@intel.com>