python3-elementpath/3.0.2: add recipe
elementpath 4.0.1 has removed 'SYMBOLS' attribute, which causing failure in ACRN 3.1.0
https://github.com/sissaschool/elementpath/commit/a76aeb88b0d103420239df1d5d001f7d7f56b5c9

misc/config_tools/scenario_config/elementpath_overlay.py", line 24, in CustomParser
|     SYMBOLS = BaseParser.SYMBOLS | {
|               ^^^^^^^^^^^^^^^^^^
| AttributeError: type object 'XPath2Parser' has no attribute 'SYMBOLS'

Issue raised: https://github.com/projectacrn/acrn-hypervisor/issues/8368

Carry python3-elementpath 3.0.2 version locally, until it gets fixed upstream

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>