doc: document required 'pam' distro_feature for weston images
Now 'pam' has become required distro feature for weston package
when systemd is init manager, which cause below acrn build failures:

Build Error:
ERROR: Nothing RPROVIDES 'weston' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-init' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-examples' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-xwayland' (but meta-acrn/recipes-core/images/acrn-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'acrn-image-weston'
ERROR: Nothing RPROVIDES 'weston' (but mc:uos:meta/recipes-graphics/images/core-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-init' (but mc:uos:meta/recipes-graphics/images/core-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-examples' (but mc:uos:meta/recipes-graphics/images/core-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'weston-xwayland' (but mc:uos:meta/recipes-graphics/images/core-image-weston.bb RDEPENDS on or otherwise requires it)
ERROR: Nothing RPROVIDES 'core-image-weston'
ERROR: Nothing PROVIDES 'core-image-weston'

Ref: https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=a51ebb8d2d30436b449aa33b91ba8dd20410002b

Also updated document for UOS wic image.

Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>